name: CI Workflow

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Use reusable build action
        uses: ./.github/actions/build-action
        with:
          node-version: '18'

      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-artifacts-${{ github.run_id }}
          path: build/

      - name: Run tests
        run: yarn test
        shell: bash


